// <auto-generated />
using System;
using Itinera.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Itinera.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Itinera.Domain.Common.EstadoFacturaCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadosFactura", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Parcialmente Pagada"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Pagada"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Anulada"
                        });
                });

            modelBuilder.Entity("Itinera.Domain.Common.EstadoPropuestaCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("EstadosPropuestas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Borrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Presentada"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Aceptada"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Rechazada"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Eliminada"
                        });
                });

            modelBuilder.Entity("Itinera.Domain.Common.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioRegistracionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Personas", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Itinera.Domain.Empresa.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Cargos", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Empresa.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioRegistracionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Facturacion.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("DetallesFactura", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Facturacion.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoFacturaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PropuestaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoFacturaId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("PropuestaId");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Facturacion.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FacturaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("DuracionEstimada")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.ToTable("Actividades", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.ActividadDestinoItinerario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("DestinoItinerarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("DestinoItinerarioId");

                    b.ToTable("ActividadesDestinoItinerario", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Ciudades", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CiudadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.ToTable("Destinos", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.DestinoItinerario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DestinoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaLlegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPartida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ItinerarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("ItinerarioId");

                    b.ToTable("DestinosItinerario", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Itinerario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PropuestaId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioRegistracionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropuestaId")
                        .IsUnique();

                    b.ToTable("Itinerarios", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Propuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoPropuestaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Presupuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioRegistracionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstadoPropuestaId");

                    b.ToTable("Propuestas", (string)null);
                });

            modelBuilder.Entity("Itinera.Security.Domain.GrupoMiembro", b =>
                {
                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uuid");

                    b.HasKey("GrupoId", "MiembroId");

                    b.HasIndex("MiembroId");

                    b.ToTable("GrupoMiembros", (string)null);
                });

            modelBuilder.Entity("Itinera.Security.Domain.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("Itinera.Security.Domain.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Itinera.Security.Domain.UsuarioComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("UsuariosSeguridad", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("UsuarioComponent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Itinera.Security.Domain.UsuarioComponentRol", b =>
                {
                    b.Property<Guid>("UsuarioComponentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioComponentId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioComponentRoles", (string)null);
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("PermisoId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("RolPermiso");
                });

            modelBuilder.Entity("Itinera.Domain.Usuarios.Cliente", b =>
                {
                    b.HasBaseType("Itinera.Domain.Common.Persona");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Itinera.Domain.Usuarios.Empleado", b =>
                {
                    b.HasBaseType("Itinera.Domain.Common.Persona");

                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.HasIndex("CargoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("Itinera.Security.Domain.GrupoUsuarios", b =>
                {
                    b.HasBaseType("Itinera.Security.Domain.UsuarioComponent");

                    b.HasDiscriminator().HasValue("Grupo");
                });

            modelBuilder.Entity("Itinera.Security.Domain.Usuario", b =>
                {
                    b.HasBaseType("Itinera.Security.Domain.UsuarioComponent");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("Itinera.Domain.Facturacion.DetalleFactura", b =>
                {
                    b.HasOne("Itinera.Domain.Facturacion.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Itinera.Domain.Facturacion.Factura", b =>
                {
                    b.HasOne("Itinera.Domain.Common.EstadoFacturaCatalogo", "EstadoFacturaCatalogo")
                        .WithMany()
                        .HasForeignKey("EstadoFacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Itinera.Domain.Propuestas.Propuesta", "Propuesta")
                        .WithMany("Facturas")
                        .HasForeignKey("PropuestaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoFacturaCatalogo");

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("Itinera.Domain.Facturacion.Pago", b =>
                {
                    b.HasOne("Itinera.Domain.Facturacion.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Actividad", b =>
                {
                    b.HasOne("Itinera.Domain.Propuestas.Destino", "Destino")
                        .WithMany("Actividades")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.ActividadDestinoItinerario", b =>
                {
                    b.HasOne("Itinera.Domain.Propuestas.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Itinera.Domain.Propuestas.DestinoItinerario", "DestinoItinerario")
                        .WithMany("ActividadDestinoItinerarios")
                        .HasForeignKey("DestinoItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("DestinoItinerario");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Ciudad", b =>
                {
                    b.HasOne("Itinera.Domain.Propuestas.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Destino", b =>
                {
                    b.HasOne("Itinera.Domain.Propuestas.Ciudad", "Ciudad")
                        .WithMany("Destinos")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.DestinoItinerario", b =>
                {
                    b.HasOne("Itinera.Domain.Propuestas.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId");

                    b.HasOne("Itinera.Domain.Propuestas.Itinerario", null)
                        .WithMany("Destinos")
                        .HasForeignKey("ItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Itinerario", b =>
                {
                    b.HasOne("Itinera.Domain.Propuestas.Propuesta", "Propuesta")
                        .WithOne("Itinerario")
                        .HasForeignKey("Itinera.Domain.Propuestas.Itinerario", "PropuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Propuesta", b =>
                {
                    b.HasOne("Itinera.Domain.Usuarios.Cliente", "Cliente")
                        .WithMany("Propuestas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Itinera.Domain.Usuarios.Empleado", "Empleado")
                        .WithMany("Propuestas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Itinera.Domain.Common.EstadoPropuestaCatalogo", "EstadoPropuestaCatalogo")
                        .WithMany()
                        .HasForeignKey("EstadoPropuestaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("EstadoPropuestaCatalogo");
                });

            modelBuilder.Entity("Itinera.Security.Domain.GrupoMiembro", b =>
                {
                    b.HasOne("Itinera.Security.Domain.GrupoUsuarios", "Grupo")
                        .WithMany("GrupoMiembros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Itinera.Security.Domain.Usuario", "Miembro")
                        .WithMany()
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("Itinera.Security.Domain.UsuarioComponentRol", b =>
                {
                    b.HasOne("Itinera.Security.Domain.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Itinera.Security.Domain.UsuarioComponent", "UsuarioComponent")
                        .WithMany()
                        .HasForeignKey("UsuarioComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("UsuarioComponent");
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.HasOne("Itinera.Security.Domain.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Itinera.Security.Domain.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Itinera.Domain.Usuarios.Cliente", b =>
                {
                    b.HasOne("Itinera.Domain.Common.Persona", null)
                        .WithOne()
                        .HasForeignKey("Itinera.Domain.Usuarios.Cliente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Itinera.Domain.Usuarios.Empleado", b =>
                {
                    b.HasOne("Itinera.Domain.Empresa.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Itinera.Domain.Empresa.Empresa", "Empresa")
                        .WithMany("Empleados")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Itinera.Domain.Common.Persona", null)
                        .WithOne()
                        .HasForeignKey("Itinera.Domain.Usuarios.Empleado", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Itinera.Domain.Empresa.Empresa", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Itinera.Domain.Facturacion.Factura", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Ciudad", b =>
                {
                    b.Navigation("Destinos");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Destino", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.DestinoItinerario", b =>
                {
                    b.Navigation("ActividadDestinoItinerarios");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Itinerario", b =>
                {
                    b.Navigation("Destinos");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Pais", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Itinera.Domain.Propuestas.Propuesta", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Itinerario");
                });

            modelBuilder.Entity("Itinera.Domain.Usuarios.Cliente", b =>
                {
                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("Itinera.Domain.Usuarios.Empleado", b =>
                {
                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("Itinera.Security.Domain.GrupoUsuarios", b =>
                {
                    b.Navigation("GrupoMiembros");
                });
#pragma warning restore 612, 618
        }
    }
}
